#!/bin/bash

conda create -y -n DFRscore python=3.9.13
conda activate DFRscore

pip install timeout-decorator
conda install -y -c conda-forge matplotlib, scipt, numpy
conda install -y -c anaconda scikit-learn
conda install -y -c rdkit rdkit=2020.09.1

conda install -y pytorch=1.11.0 cudatoolkit=10.2 -c pytorch
#conda install -y pytorch=1.11.0 cudatoolkit=11.3 -c pytorch
#conda install -y pytorch=1.11.0 -c pytorch
