#!/bin/bash

micromamba create -y -n DFRscore python=3.9.13
micromamba activate DFRscore

pip install timeout-decorator
micromamba install -y -c conda-forge matplotlib, scipt, numpy
micromamba install -y -c anaconda scikit-learn
micromamba install -y -c rdkit rdkit=2020.09.1

micromamba install -y pytorch=1.11.0 cudatoolkit=10.2 -c pytorch
#micromamba install -y pytorch=1.11.0 cudatoolkit=11.3 -c pytorch
#micromamba install -y pytorch=1.11.0 -c pytorch
