#!/bin/bash
CONDA_BASE=$(conda info --base)
conda create -y -n SVS python=3.6
source $CONDA_BASE/etc/profile.d/conda.sh
conda activate SVS

# 1. for Retro-analysis
conda install -y -c rdkit rdkit=2020.09.1

# 2. for Training model
conda install -y -c conda-forge scipy
conda install -y -c conda-forge numpy
conda install -y -c anaconda scikit-learn
conda install -y pytorch cudatoolkit=10.2 -c pytorch
#conda install -y pytorch -c pytorch
